/**
 * Centralized Cloudinary Asset URLs for Frontend
 */

export const CLOUDINARY_ASSETS = {
  "whatsapp_image_2026_07_09_at_12_56_20_pm_2_jpeg": "https://media.zoniraz.com/uploads/zoniraz_frontend/WhatsApp_Image_2026-07-09_at_12_56_20_PM__2_.jpg",
  "banner_2_jpg_jpeg": "https://media.zoniraz.com/uploads/zoniraz_frontend/banner_2_jpg.jpg",
  "empty_vtt": "https://media.zoniraz.com/uploads/zoniraz_frontend/empty.vtt",
  "gold_banner__jpg_jpeg": "https://media.zoniraz.com/uploads/zoniraz_frontend/gold_banner__jpg.jpg",
  "jewelry_banner_1_png": "https://media.zoniraz.com/uploads/zoniraz_frontend/jewelry_banner_1.png",
  "zoni_png": "https://media.zoniraz.com/uploads/zoniraz_frontend/zoni.png",
  "zoni1_png": "https://media.zoniraz.com/uploads/zoniraz_frontend/zoni1.png",
  "zoniraz_banner_5_jpg_jpeg": "https://media.zoniraz.com/uploads/zoniraz_frontend/zoniraz_banner_5_jpg.jpg",
  "wedding_banner_png": "https://media.zoniraz.com/uploads/zoniraz_frontend/WEDDING_BANNER.png",
  "whatsapp_image_2026_07_24_at_12_32_04_pm_1_jpeg": "https://media.zoniraz.com/uploads/zoniraz_frontend/WhatsApp_Image_2026-07-24_at_12_32_04_PM__1_.jpg",
  "whatsapp_image_2026_07_24_at_12_32_04_pm_jpeg": "https://media.zoniraz.com/uploads/zoniraz_frontend/WhatsApp_Image_2026-07-24_at_12_32_04_PM.jpg",
  "whatsapp_image_2026_07_24_at_12_32_05_pm_1_jpeg": "https://media.zoniraz.com/uploads/zoniraz_frontend/WhatsApp_Image_2026-07-24_at_12_32_05_PM__1_.jpg",
  "whatsapp_image_2026_07_24_at_12_32_05_pm_jpeg": "https://media.zoniraz.com/uploads/zoniraz_frontend/WhatsApp_Image_2026-07-24_at_12_32_05_PM.jpg",
  "whatsapp_image_2026_07_24_at_12_32_06_pm_1_jpeg": "https://media.zoniraz.com/uploads/zoniraz_frontend/WhatsApp_Image_2026-07-24_at_12_32_06_PM__1_.jpg",
  "whatsapp_image_2026_07_24_at_12_32_06_pm_2_jpeg": "https://media.zoniraz.com/uploads/zoniraz_frontend/WhatsApp_Image_2026-07-24_at_12_32_06_PM__2_.jpg",
  "whatsapp_image_2026_07_24_at_12_32_06_pm_jpeg": "https://media.zoniraz.com/uploads/zoniraz_frontend/WhatsApp_Image_2026-07-24_at_12_32_06_PM.jpg",
  "whatsapp_image_2026_07_24_at_12_32_07_pm_1_jpeg": "https://media.zoniraz.com/uploads/zoniraz_frontend/WhatsApp_Image_2026-07-24_at_12_32_07_PM__1_.jpg",
  "whatsapp_image_2026_07_24_at_12_32_07_pm_jpeg": "https://media.zoniraz.com/uploads/zoniraz_frontend/WhatsApp_Image_2026-07-24_at_12_32_07_PM.jpg",
  "aneka_png": "https://media.zoniraz.com/uploads/zoniraz_frontend/aneka.jpg",
  "caratlane_iconics_png": "https://media.zoniraz.com/uploads/zoniraz_frontend/caratlane-iconics.jpg",
  "collection_banner_1_png": "https://media.zoniraz.com/uploads/zoniraz_frontend/collection-banner-1.png",
  "consultation_desk_png": "https://media.zoniraz.com/uploads/zoniraz_frontend/consultation-desk.jpg",
  "customer_favourites_png": "https://media.zoniraz.com/uploads/zoniraz_frontend/customer-favourites.jpg",
  "dancing_hoops_png": "https://media.zoniraz.com/uploads/zoniraz_frontend/dancing-hoops.jpg",
  "gift_cards_png": "https://media.zoniraz.com/uploads/zoniraz_frontend/gift-cards.jpg",
  "gifts_for_mom_png": "https://media.zoniraz.com/uploads/zoniraz_frontend/gifts-for-mom.jpg",
  "gold_earrings_banner_jpg": "https://media.zoniraz.com/uploads/zoniraz_frontend/gold-earrings-banner.jpg",
  "gold_necklace_silk_png": "https://media.zoniraz.com/uploads/zoniraz_frontend/gold-necklace-silk.jpg",
  "gold_zodiac_banner_jpg": "https://media.zoniraz.com/uploads/zoniraz_frontend/gold-zodiac-banner.jpg",
  "gulnaara_png": "https://media.zoniraz.com/uploads/zoniraz_frontend/gulnaara.jpg",
  "heart_fusion_ring_png": "https://media.zoniraz.com/uploads/zoniraz_frontend/heart_fusion_ring.jpg",
  "hero_model_png": "https://media.zoniraz.com/uploads/zoniraz_frontend/hero-model.png",
  "infinity_necklaces_png": "https://media.zoniraz.com/uploads/zoniraz_frontend/infinity-necklaces.jpg",
  "infinity_diamond_ring_png": "https://media.zoniraz.com/uploads/zoniraz_frontend/infinity_diamond_ring.jpg",
  "kids_1400_webp": "https://media.zoniraz.com/uploads/zoniraz_frontend/kids-1400.webp",
  "kids_800_webp": "https://media.zoniraz.com/uploads/zoniraz_frontend/kids-800.webp",
  "layered_necklaces_png": "https://media.zoniraz.com/uploads/zoniraz_frontend/layered-necklaces.jpg",
  "lotus_bypass_ring_png": "https://media.zoniraz.com/uploads/zoniraz_frontend/lotus_bypass_ring.jpg",
  "mangalsutra_earrings_png": "https://media.zoniraz.com/uploads/zoniraz_frontend/mangalsutra-earrings.jpg",
  "mens_1400_webp": "https://media.zoniraz.com/uploads/zoniraz_frontend/mens-1400.webp",
  "mens_800_webp": "https://media.zoniraz.com/uploads/zoniraz_frontend/mens-800.webp",
  "mens_platinum_png": "https://media.zoniraz.com/uploads/zoniraz_frontend/mens-platinum.jpg",
  "mesh_cluster_ring_png": "https://media.zoniraz.com/uploads/zoniraz_frontend/mesh_cluster_ring.jpg",
  "message_bands_png": "https://media.zoniraz.com/uploads/zoniraz_frontend/message-bands.jpg",
  "nine_kt_png": "https://media.zoniraz.com/uploads/zoniraz_frontend/nine-kt.jpg",
  "postcards_banner_png": "https://media.zoniraz.com/uploads/zoniraz_frontend/postcards-banner.jpg",
  "shaya_diamonds_png": "https://media.zoniraz.com/uploads/zoniraz_frontend/shaya-diamonds.jpg",
  "silver_bracelets_png": "https://media.zoniraz.com/uploads/zoniraz_frontend/silver-bracelets.jpg",
  "silver_earrings_png": "https://media.zoniraz.com/uploads/zoniraz_frontend/silver-earrings.jpg",
  "silver_necklaces_png": "https://media.zoniraz.com/uploads/zoniraz_frontend/silver-necklaces.jpg",
  "silver_rings_png": "https://media.zoniraz.com/uploads/zoniraz_frontend/silver-rings.jpg",
  "solitaire_sets_png": "https://media.zoniraz.com/uploads/zoniraz_frontend/solitaire-sets.jpg",
  "stretchable_bangles_png": "https://media.zoniraz.com/uploads/zoniraz_frontend/stretchable-bangles.jpg",
  "switch_earrings_png": "https://media.zoniraz.com/uploads/zoniraz_frontend/switch-earrings.jpg",
  "trendy_mangalsutras_webp": "https://media.zoniraz.com/uploads/zoniraz_frontend/trendy-mangalsutras.webp",
  "1_mp4": "https://media.zoniraz.com/uploads/zoniraz_frontend/videos/1.mp4",
  "3_mp4": "https://media.zoniraz.com/uploads/zoniraz_frontend/videos/3.mp4",
  "4_mp4": "https://media.zoniraz.com/uploads/zoniraz_frontend/videos/4.mp4",
  "5_optimized_mp4": "https://media.zoniraz.com/uploads/zoniraz_frontend/videos/5-optimized.mp4",
  "5_optimized_webm": "https://media.zoniraz.com/uploads/zoniraz_frontend/videos/5-optimized.webm",
  "5_poster_webp": "https://media.zoniraz.com/uploads/zoniraz_frontend/videos/5-poster.webp",
  "6_mp4": "https://media.zoniraz.com/uploads/zoniraz_frontend/videos/6.mp4",
  "9_mp4": "https://media.zoniraz.com/uploads/zoniraz_frontend/videos/9.mp4",
  "bangles_mp4": "https://media.zoniraz.com/uploads/zoniraz_frontend/videos/Bangles.mp4",
  "d92d747b23c8205d85da43cb7d302733_mp4": "https://media.zoniraz.com/uploads/zoniraz_frontend/videos/d92d747b23c8205d85da43cb7d302733.mp4",
  "daleywear_mp4": "https://media.zoniraz.com/uploads/zoniraz_frontend/videos/daleywear.mp4",
  "heritagegold_mp4": "https://media.zoniraz.com/uploads/zoniraz_frontend/videos/heritageGold.mp4",
  "neck_mp4": "https://media.zoniraz.com/uploads/zoniraz_frontend/videos/neck.mp4",
  "officewear_mp4": "https://media.zoniraz.com/uploads/zoniraz_frontend/videos/officewear.mp4",
  "zoniraz_ring__mp4": "https://media.zoniraz.com/uploads/zoniraz_frontend/videos/zoniraz_ring_.mp4",
  "watch_charms_png": "https://media.zoniraz.com/uploads/zoniraz_frontend/watch-charms.jpg",
  "wear_your_wins_png": "https://media.zoniraz.com/uploads/zoniraz_frontend/wear-your-wins.jpg",
  "women_1400_webp": "https://media.zoniraz.com/uploads/zoniraz_frontend/women-1400.webp",
  "women_800_webp": "https://media.zoniraz.com/uploads/zoniraz_frontend/women-800.webp",
  "yellow_gold_nose_pin_banner_png": "https://media.zoniraz.com/uploads/zoniraz_frontend/yellow-gold-nose-pin-banner.jpg",
  "yellow_gold_solitaire_banner_png": "https://media.zoniraz.com/uploads/zoniraz_frontend/yellow-gold-solitaire-banner.jpg",
  "zzoniraz_1400_webp": "https://media.zoniraz.com/uploads/zoniraz_frontend/zZONIRAZ-1400.webp",
  "zzoniraz_800_webp": "https://media.zoniraz.com/uploads/zoniraz_frontend/zZONIRAZ-800.webp",
};

export default CLOUDINARY_ASSETS;
